spring:
  config:
    import: 'consul:'
  application:
    name: producer-service

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        hostname: host.docker.internal
        instance-id: producer-service
        acl-token: 45cb0de0-6d6c-6545-477c-08f2e6d529cb
      config:
        data-key: data
        format: yaml
        acl-token: 45cb0de0-6d6c-6545-477c-08f2e6d529cb


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - metrics
          - info
server:
  port: 8182