version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: salas
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: salas
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://salas:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - mongo-net


  consul:
    image: consul:1.15.4
    container_name: consul-server-1
    ports:
      - "8500:8500"     # Web UI и HTTP API
      - "8600:8600/udp" # DNS (опционально)
    volumes:
      - ./tmp/consul/salas_project_consul_data:/consul/data
      - ./tmp/consul/config:/consul/config
    command:
      - agent
      - -server
      - -ui
      - -client=0.0.0.0
      - -data-dir=/consul/data
      - -bootstrap-expect=1
      - -config-file=/consul/config/agent.json
    networks:
      - mongo-net

volumes:
  mongo: {}

networks:
  mongo-net:
