version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: salas
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: salas
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://salas:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - mongo-net


  consul:
    image: consul:1.15.4
    container_name: consul-server-1
    ports:
      - "8500:8500"     # Web UI и HTTP API
      - "8600:8600/udp" # DNS (опционально)
    volumes:
      - ./tmp/consul/salas_project_consul_data:/consul/data
      - ./tmp/consul/config:/consul/config
    command:
      - agent
      - -server
      - -ui
      - -client=0.0.0.0
      - -data-dir=/consul/data
      - -bootstrap-expect=1
      - -config-file=/consul/config/agent.json
    networks:
      - mongo-net


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-for-home-work
    ports:
      - '9090:9090'
    volumes:
      - ./tmp/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mongo-net


  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-for-home-work
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - mongo-net
    volumes:
      - ./tmp/grafana-storage:/var/lib/grafana
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  mongo: {}

networks:
  mongo-net:
