server:
  port: 8191

spring:
  application:
    name: event-consumer
  config:
    import: 'consul:'

  cloud:
    consul:
      port: 8500
      host: consul-server-1
      discovery:
        hostname: event-consumer
        instance-id: event-consumer
        acl-token: e93f1f1c-bd9e-b501-c657-1e27aea1292c
      config:
        data-key: data
        format: yaml
        acl-token: e93f1f1c-bd9e-b501-c657-1e27aea1292c

  datasource:
    url: jdbc:postgresql://postgres:5432/events_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka1:29092,kafka2:29093,kafka3:29094
    consumer:
      group-id: event-group
    properties:
      schema.registry.url: http://schema-registry:8081
      specific.avro.reader: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0
#    otlp:
#      endpoint: http://alloy:4318
#      protocol: http/protobuf

