#server:
#  port: 8192

spring:
  config:
    import: 'consul:'
  application:
    name: event-producer


  cloud:
    consul:
      port: 8500
      host: consul-server-1
      discovery:
        hostname: event-producer
        instance-id: event-producer
        acl-token: 381f9819-96a5-0f67-4521-f0fe915f47c3
      config:
        data-key: data
        format: yaml
        acl-token: 381f9819-96a5-0f67-4521-f0fe915f47c3

  kafka:
    bootstrap-servers: kafka1:29092,kafka2:29093,kafka3:29094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://schema-registry:8081
event:
  topic: events
  generation:
    interval-ms: 1000  # Интервал генерации событий (1 сообщение в секунду)

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true