spring:
  application:
    name: mongodb-service
  config:
    import: 'consul:'

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        hostname: host.docker.internal
        instance-id: mongo-db-service
        acl-token: 14e4d5ac-fc1c-f9b5-54d4-4cfc9143ed1d
      config:
        acl-token: 14e4d5ac-fc1c-f9b5-54d4-4cfc9143ed1d
        format: yaml
        data-key: data #default-value

server:
  port: 8180


grpc:
  server:
    port: 9090

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - metrics
          - info
