spring:
  application:
    name: mongodb-service
  data:
    mongodb:
      username: salas
      password: password
      host: mongodb
      port: 27017
      database: magazinecoding
      authentication-database: admin

server:
  port: 8180


grpc:
  server:
    port: 9090
