server:
  port: 8192

spring:
  application:
    name: event-public-api

management:
  server:
    port: 8192
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true


event-consumer:
  url: http://event-consumer:8091
